language: python

python:
  - "2.7"

install:
  - pip install -q -r requirements.txt
  - pip install -q coverage
  - pip install -q coveralls

script:
  - nosetests pelican_jsfiddle --with-coverage --cover-package=pelican_jsfiddle

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
  email: false
