language: python

python:
  - "2.7"

install:
  - pip install -q -r requirements.txt
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q nose-cov

script:
  - nosetests --with-cov --cov-config .coveragerc --cov-report term --cov pelican_jsfiddle 

after_success:
  - coveralls

branches:
  only:
    - master

notifications:
  email: false
